GET http://localhost:5000/api/users

###

POST http://localhost:5000/api/users
Content-Type: application/json

{
  "firstName": "Babajee",
  "lastName": "Sefu",
  "age": 20
}

###

PUT  http://localhost:5000/api/users/637bb44f1e44dd2541b5961d
Content-Type: application/json

{
  "firstName": "yo",
  "lastName": "let's go",
  "age": 60
}

###

DELETE http://localhost:5000/api/users/637bb44f1e44dd2541b5961d